"$schema" = 'https://starship.rs/config-schema.json'

#add_newline = true
command_timeout = 5000

format = """
$os$hostname$directory$git_branch$aws$cmd_duration
$character
"""

[aws]
symbol = " "
format = '[$symbol($profile )(\($region\) )](bold yellow)'

[aws.region_aliases]
ap-southeast-2 = 'syd'
us-east-1 = 'iad'
ca-central-1 = 'yul'
us-west-2 = 'pdx'
us-east-2 = 'cmh'
us-west-1 = 'sfo'
sa-east-1 = 'gru'
eu-west-1 = 'dub'
eu-central-1 = 'fra'
eu-central-2 = 'zrh'

[hostname]
ssh_only = false
format = '[$hostname ](bold white)'
disabled = false

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[\[$user\]]($style)'
disabled = false
show_always = true

[cmd_duration]
format = 'took [$duration](bold white)'

[directory]
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = "~/…/"
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style) '

[localip]
ssh_only = true
format = '[$localipv4](bold) '
disabled = false

[docker_context]
symbol = " "

[git_branch]
symbol = " "
format = 'on [$symbol$branch]($style) '

[golang]
symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[os]
disabled = false
#format = '[$symbol](bold white) '

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "
